apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery
  template:
    metadata:
      labels:
        app: delivery
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: delivery
          image: 496278789073.dkr.ecr.ap-northeast-1.amazonaws.com/skccuser02-delivery:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/deliveries'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/deliveries'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
